spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  csv:
    export:
      directory=C:/csv-files:
