spring:
  datasource:
    url: jdbc:oracle:thin:@10.10.10.93:1521:daa
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  csv:
    export:
      directory=C:/csv-files:
